//
// Generated file, do not edit! Created by nedtool 5.6 from AircraftPacket.msg.
//

#ifndef __AIRCRAFTPACKET_M_H
#define __AIRCRAFTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>AircraftPacket.msg:1</tt> by nedtool.
 * <pre>
 * packet AircraftPacket
 * {
 *     int aircraftID;
 *     simtime_t sendTime;
 *     simtime_t arrivalTime;
 * }
 * </pre>
 */
class AircraftPacket : public ::omnetpp::cPacket
{
  protected:
    int aircraftID;
    ::omnetpp::simtime_t sendTime;
    ::omnetpp::simtime_t arrivalTime;

  private:
    void copy(const AircraftPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AircraftPacket&);

  public:
    AircraftPacket(const char *name=nullptr, short kind=0);
    AircraftPacket(const AircraftPacket& other);
    virtual ~AircraftPacket();
    AircraftPacket& operator=(const AircraftPacket& other);
    virtual AircraftPacket *dup() const override {return new AircraftPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getAircraftID() const;
    virtual void setAircraftID(int aircraftID);
    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);
    virtual ::omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(::omnetpp::simtime_t arrivalTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AircraftPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AircraftPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __AIRCRAFTPACKET_M_H

